from train_test_split import train_test_split_save
from convert_images_to_labels_pcds import convert_images_to_labels_pcds

for_jackle = False
convert_images_to_labels_pcds(for_jackle)
train_test_split_save(for_jackle)